# Generated by Django 5.1.5 on 2025-01-31 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('endereco', models.CharField(max_length=30)),
                ('cep', models.IntegerField()),
                ('cnpj', models.IntegerField()),
                ('codigo', models.IntegerField()),
                ('prefixo_ramal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet_api.loja')),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('ramal', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet_api.loja')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet_api.setor')),
            ],
            options={
                'verbose_name_plural': 'Contatos',
                'ordering': ['setor'],
            },
        ),
    ]
