# Generated by Django 5.1.5 on 2025-02-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='endereco',
            field=models.CharField(max_length=90),
        ),
    ]
