# Generated by Django 5.1.5 on 2025-02-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet_api', '0003_alter_loja_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='nome',
            field=models.CharField(max_length=60),
        ),
    ]
