# Generated by Django 5.1.5 on 2025-02-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet_api', '0004_alter_contato_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contato',
            name='ramal',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
