# Generated by Django 5.1.5 on 2025-02-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet_api', '0005_alter_contato_email_alter_contato_ramal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
